more portable way to generate the man pages from docbook files

diff --git a/doc/Makefile.in b/doc/Makefile.in
--- a/doc/Makefile.in
+++ b/doc/Makefile.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-# $Id: Makefile.in,v 1.3 2002-01-03 14:44:36 thib Exp $
+# $Id: Makefile.in,v 1.4 2002-01-03 22:39:50 thib Exp $
 
 # The following should not be edited manually (use configure options)
 # If you must do it, BEWARE : some of the following is also defined
@@ -20,8 +20,13 @@ DESTDOC		= @DOCDIR@
 
 INSTALL		= @INSTALL@
 JADE 		= @JADE@
+NSGMLS		= @NSGMLS@
+SGMLSPL		= @SGMLSPL@
+DB2MAN_SPEC	= @DB2MAN_SPEC@
+
 ROOTNAME	= @ROOTNAME@
 ROOTGROUP	= @ROOTGROUP@
+
 ANSWERALL	= @ANSWERALL@
 
 ####################################
@@ -43,6 +48,12 @@ all: doc
 doc: HTML/index.html
 
 mandoc: HTML/index.html
+	@(if test \( ! -f $(DB2MAN_SPEC) \) -o \( ! -x $(NSGMLS) \) -o \( ! -x $(SGMLSPL) \); then \
+	   echo "ERROR: cannot generate man pages." ; \
+	   echo "       Please check if nsgmls, sgmlspl are installed, and " ; \
+	   echo "       if configure's option --with-db2man-spec is correctly set." ; \
+	   exit 1 ; \
+	fi)
 	@(echo ; echo "Building man pages ..."; echo )
 	cp -f bitstring.3 man/
 	@(for i in $(MANPAGES); do \
@@ -51,10 +62,11 @@ mandoc: HTML/index.html
                   <!ENTITY % decl SYSTEM "fcron-doc.mod"> \
                   %decl;]>' > _tmp_ ; \
           echo "&$$i;" >> _tmp_ ; \
-          jw -f docbook -b man -o man _tmp_ 2> /dev/null; \
+          $(NSGMLS) _tmp_ 2> /dev/null | $(SGMLSPL) $(DB2MAN_SPEC) 2>&1 > /dev/null ; \
 	  rm -f _tmp_ ; \
+	  mv `basename $$i .sgml` man/ ; \
           done)
-	rm -f man/manpage.links man/manpage.refs
+	rm -f manpage.links manpage.refs
 
 
 txtdoc: HTML/index.html
