added ./configure's option --with-answer-all

diff --git a/script/user-group b/script/user-group
--- a/script/user-group
+++ b/script/user-group
@@ -4,57 +4,66 @@
 #  them if necessary.
 #
 
-# $Id: user-group,v 1.2 2001-01-04 15:50:41 thib Exp $
+# $Id: user-group,v 1.3 2001-01-07 12:45:38 thib Exp $
 
-# take 2 arguments : 	username
+# take 3 arguments : 	username
 # 			groupname
+#                       automatic answer
 
 PATH="/sbin:/usr/sbin:/bin:/usr/bin:/usr/X11R6/bin"
 
-if test $# -ne 2; then
+if test $# -ne 3; then
     echo "Too few/many arguments"
     exit 1
 fi
 
 USERNAME=$1
 GROUPNAME=$2
+ANSWER=$3
 INSTALL="nothing"
 INSTALLED=0
 
 echo -n "Checking if $USERNAME is in /etc/passwd ... "
 if grep "^$USERNAME:" /etc/passwd > /dev/null; then
-    echo "yes."
-    INSTALLED=1
+  echo "yes."
+  INSTALLED=1
 else
-    echo "no."
-    CMD=""
-    if useradd -D 2> /dev/null; then
-	CMD="useradd -c 'fcron' fcron"
-    elif adduser -D 2> /dev/null; then
-	CMD="adduser -c 'fcron' fcron"
-    fi
-    if test -z "$CMD"; then
-	echo "Could not determine the command to use to add a user."
-	echo "Please add user \"$USERNAME\" (group \"GROUPNAME\") manually"
-	echo "(or choose another username with configure script)."
-	exit 1
-    fi
+  echo "no."
+  CMD=""
+  if useradd -D 2> /dev/null; then
+    CMD="useradd -c 'fcron' fcron"
+  elif adduser -D 2> /dev/null; then
+    CMD="adduser -c 'fcron' fcron"
+  fi
+  if test -z "$CMD"; then
+    echo "Could not determine the command to use to add a user."
+    echo "Please add user \"$USERNAME\" (group \"GROUPNAME\") manually"
+    echo "(or choose another username with configure script)."
+    exit 1
+  fi
+  if test $ANSWER -eq 2; then
     while test \( ! -z "$INSTALL" \) -a \( "$INSTALL" != "y" \) -a \( "$INSTALL" != "n" \);
-	do
-	    echo "Would you like to add $USERNAME in /etc/passwd with the following command ?"
-	echo "    $CMD"
-	read -p "Please answer with 'y' or 'n' (default: 'y'): " INSTALL NOTHING
-	done
+    do
+      echo "Would you like to add $USERNAME in /etc/passwd with the following command ?"
+      echo "    $CMD"
+      read -p "Please answer with 'y' or 'n' (default: 'y'): " INSTALL NOTHING
+    done
     if test \( -z "$INSTALL" \) -o \( "$INSTALL" = "y" \); then
-	if $CMD; then
-	    INSTALLED=1
-	fi
-    fi    
+      if $CMD; then
+        INSTALLED=1
+      fi
+    fi
+  elif test $ANSWER -eq 1; then
+    # automatic answer given by configure script (option --with-answer-all)
+    if $CMD; then
+      INSTALLED=1
+    fi
+  fi    
 fi
 
 
 if test $INSTALLED -eq 0; then
-    echo "User $USERNAME does not exist : please create it or choose another username"
-    echo "with configure script."
-    exit 1
+  echo "User $USERNAME does not exist : please create it or choose another username"
+  echo "with configure script."
+  exit 1
 fi
